drivers: Move more SECTOR_SIZE definitions into <linux/blkdev.h>
Introduces after d24c407b0f7af675a3928fdd4121306ad32c60ab.

Fix error:

    ../drivers/md/dm-req-crypt.c:54:9: error: 'SECTOR_SIZE' macro redefined [-Werror,-Wmacro-redefined]
            ^
    ../include/linux/blkdev.h:871:9: note: previous definition is here
            ^
    1 error generated.

    ../drivers/md/dm-bow.c:15:9: error: 'SECTOR_SIZE' macro redefined [-Werror,-Wmacro-redefined]
            ^
    ../include/linux/blkdev.h:871:9: note: previous definition is here
            ^
    1 error generated.